### ISSUE TITLE
Missing authorisation in A14

### ISSUE THREAD

**Issue by SiggiKg** [nearby-sharing/android#129] opened 2024-01-24 10:51 UTC
Hi,

I get an error message when receiving on Android 14,  pictures attached .

[Screenshot_20240124-104606](https://github.com/nearby-sharing/android/assets/7691130/8aa7729a-8666-4be2-88b0-03ddae794ac5)
[Screenshot_20240124-104916](https://github.com/nearby-sharing/android/assets/7691130/23fb33a8-e050-45e0-92d8-13763bbf6a8c)

**Comment by ShortDevelopment** [comment] 2024-01-24 11:22
What app-version are you using?

**Comment by ShortDevelopment** [comment] 2024-01-24 11:22
What app-version are you using?

**Comment by SiggiKg** [comment] 2024-01-24 11:30
…

Die Version ist 1.7.0.

Was noch toll wäre eine Möglichkeit das Zielverzeichnis festzulegen (z.B. Downloads/Nearby Share)

Viele Grüße



Von: Lukas Kurz
Gesendet: Mittwoch, 24. Januar 2024 12:23
An: nearby-sharing/android
Cc: SiggiK; Author
Betreff: Re: [nearby-sharing/android] Missing authorisation in A14 (Issue#129)

What app-version are you using?

**Comment by ShortDevelopment** [comment] 2024-01-24 11:35
Could you please send me the logs from android internal storage: `/Android/media/de.shortdev.nearby_sharing_windows/logs/`?

**Comment by SiggiKg** [comment] 2024-01-24 11:45
Von: Lukas Kurz
Gesendet: Mittwoch, 24. Januar 2024 12:35
An: nearby-sharing/android
Cc: SiggiK; Author
Betreff: Re: [nearby-sharing/android] Missing authorisation in A14 (Issue#129)

Could you please send me the logs from android internal storage: /Android/media/de.shortdev.nearby_sharing_windows/logs/?

**Comment by ShortDevelopment** [comment] 2024-01-24 11:47
Sadly, GitHub does not seem to support uplaoding email attachments.
Could you please send it directly to my email address: nearshare@shortdev.de ?

**Comment by ShortDevelopment** [comment] 2024-01-24 11:54
Android 14 automatically denies the following 2 permissions
- `android.permission.READ_EXTERNAL_STORAGE`
- `android.permission.WRITE_EXTERNAL_STORAGE`

Duplicate of #124

**Closed by ShortDevelopment** 2024-01-24 11:54 UTC
