### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by xmha97** [nearby-sharing/android#106] opened 2023-08-11 15:46 UTC
Please add the dark theme to this app.

**Comment by ShortDevelopment** [comment] 2023-08-11 16:08
Dark theme is already supported in the [preview version] (https://nearshare.shortdev.de/docs/download)

Duplicate of #38

**Closed** 2023-08-11 16:08 UTC
Labels: duplicate, feature-request, UI

**Comment by xmha97** [comment] 2023-08-11 19:01
Thanks for the dark theme 🖤

![Screenshot_2023-08-11-22-30-36-574_de.shortdev.nearby_sharing_windows.jpg](https://github.com/nearby-sharing/android/assets/23485114/058feecb-f002-43cb-a769-c88dfc6fae3b)
