### ISSUE TITLE
Use system notification to accept receiving requests

### ISSUE THREAD

**Issue by QWERT-commits** [nearby-sharing/android#47] opened 2023-02-11 02:16 UTC
Currently, receiving requests can only be accepted if you open the app and click on the "Accept" option.
If the app stays in the background and pop up a notification that allow users to accept/reject files sent by the PC, it would be more similar to the nearby sharing experience between PC.

**Comment by ShortDevelopment** [comment] 2023-02-11 10:15
Depends on #41

**Comment by ShortDevelopment** [comment] 2023-08-13 09:09
Duplicate of #41

**Closed by ShortDevelopment** 2023-08-13 09:09 UTC
Labels: feature-request, UI, NearShare-Receive
